# Generated by Django 3.2.18 on 2023-04-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Құлыпқа қарсы тежегіш жүйесі', 'Құлыпқа қарсы тежегіш жүйесі'), ('Қозғалтқышқа қызмет көрсету', 'Қозғалтқышқа қызмет көрсету'), ('Автомобильді комплекс Жуу', 'Автомобильді комплекс Жуу'), ('Батарея Ауыстыру', 'Батарея Ауыстыру'), ('Май және фильтр Ауыстыру', 'Май және фильтр Ауыстыру'), ('Шиналарды жөндеу және Ауыстыру', 'Шиналарды жөндеу және Ауыстыру')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Күтілуде', 'Күтілуде'), ('Қабылданды', 'Қабылданды'), ('Жөнделу процессы', 'Жөнделу процессы'), ('Сәтті аяқталды', 'Сәтті аяқталды'), ('Қызмет қабылданды', 'Қызмет қабылданды')], default='Күтілуде', max_length=50, null=True),
        ),
    ]
